### PR TITLE
Add syntax highlighting and fix stream view results example

### PR DESCRIPTION
**Pull request by optikfluffel**

### CODE REVIEW

**Comment by benoitc** [comment]
Thanks for your patch! However, the README is generated from the overview, can you apply your
changes there?

**Comment by optikfluffel** [comment]
Like this?

**Comment by benoitc** [comment]
@optikfluffel build was failing if I was not using it for me. Does it work for you with `````?

**Comment by optikfluffel** [comment]
When I try to run `make doc` it does even fail with the `'''`:

    /usr/local/bin/rebar -C rebar_dev.config get-deps
    ==> jsx (get-deps)
    ==> oauth (get-deps)
    ==> idna (get-deps)
    ==> ssl_verify_hostname (get-deps)
    ==> hackney (get-deps)
    ==> edown (get-deps)
    ==> couchbeam (get-deps)
    /usr/local/bin/rebar -C rebar_dev.config compile
    ==> jsx (compile)
    ==> oauth (compile)
    ==> idna (compile)
    ==> ssl_verify_hostname (compile)
    ==> hackney (compile)
    ==> edown (compile)
    /Users/user/Desktop/couchbeam/deps/edown/src/edown_doclet.erl:116: field packages undefined in record doclet_gen
    /Users/user/Desktop/couchbeam/deps/edown/src/edown_doclet.erl:118: field filemap undefined in record doclet_gen
    Compiling /Users/user/Desktop/couchbeam/deps/edown/src/edown_doclet.erl failed:
    ERROR: compile failed while processing /Users/user/Desktop/couchbeam/deps/edown: rebar_abort
    make: *** [devbuild] Error 1

**Comment by benoitc** [comment]
hrm odd... In another project I directly used a `pre` but maybe it can solved in a smarter way. I will have a look.

**Comment by optikfluffel** [comment]
i can wait

**Comment by benoitc** [comment]
Sorry. I will have a look on it later in the day.

**Comment by optikfluffel** [comment]
Any updates on that one? 😅

**Pull request merged**
